### ISSUE TITLE
Evaluate if the scenarios dir on freelens repo is needed

### ISSUE THREAD

**Issue by robertobandini** [freelensapp/freelens#30]
As in the title

**Comment by robertobandini** [comment]
@dex4er Do you agree that this directory with its files is actually useless or you have some evidence that is needed?
https://github.com/freelensapp/freelens/tree/main/scenarios

**Comment by dex4er** [comment]
I removed most of the documents that should belong maybe to some wiki rather be in the code.

I would remove it too.

**Comment by robertobandini** [comment]
Great! I've removed the /scenarios dir.
