### ISSUE TITLE
Bundled kubectl should be up-to-date

### ISSUE THREAD

**Issue by dex4er** [freelensapp/freelens#32]
The bundled kubectl is 1.23.3. It misses some important feature when used with the newer Kubernetes. Ie. 1.31.0 introduced websockets protocol for port-forward.

We should probably bundle the newest kubectl as the default option (ie. 1.31.1 currently).

**Comment by robertobandini** [comment]
I agree, are you already working on that? Anyway I've assigned to you this issue, let me know if it's ok for you.
