### ISSUE TITLE
CI: Checking kubectl versions should be outside build task

### ISSUE THREAD

**Issue by dex4er** [freelensapp/freelens#41]
Checking kubectl versions should be outside the "build" target:

* it fails sometimes: https://github.com/dex4er/freelens-nightly-builds/actions/runs/11394027590/job/31703525628#step:17:783
* it updates manifest with kubectl versions outside Git flow: the binary is built with files not-in-sync with the repo

We should have separate workflow that runs it periodically then creates MR with updates.

**Comment by dex4er** [comment]
Hello @robertobandini

https://github.com/freelensapp/freelens/actions/runs/11474485789/job/31930482365 failed because it can't create PR.

Can you enable `Allow GitHub Actions to create and approve pull requests` in the settings for Actions, please?

**Comment by robertobandini** [comment]
Hi @dex4er I saw, that's ok, now that option is enabled.
Please check and let me know.

**Comment by dex4er** [comment]
All is fine. New kubectl releases generated a new PR correctly.
